{% set name = "pyxrf" %}
{% set version = "0.0.9.7" %}
{% set sha256 = "bc7d33731973985d431540109630a9098ecbe4234a0199486c541ba155909241" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/NSLS-II/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  entry_points:
    - pyxrf = pyxrf.gui:run
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - atom
    - enaml >=0.10.3
    - h5py
    - ipywidgets
    - jupyter
    - lmfit >=0.8.3
    - matplotlib
    - numpy
    - pandas
    - pillow
    - pyqt >=5.9.2
    - scipy
    - six
    - scikit-beam >=0.0.17
    - scikit-image

test:
  imports:
    - {{ name }}

about:
  home: https://github.com/NSLS-II/pyxrf
  license: 3-Clause BSD
  license_family: BSD
  license_file: LICENSE
  summary: 'Python-based sophisticated fluorescence analysis package for fitting and visualizing X-ray fluorescence data'
