{% set name = "pyxrf" %}
{% set version = "0.0.17" %}
{% set sha256 = "f3b7742e2779c1fc88db673a8568a056fb561a18c35b6b805a3c724ecb113fa1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  entry_points:
    - pyxrf = pyxrf.gui:run
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - atom
    - enaml >=0.10.3
    - h5py >=2.9.0
    - ipywidgets
    - jupyter
    - lmfit >=0.8.3
    - matplotlib
    - numpy
    - pandas
    - pillow
    - pyqt >=5.9.2
    - pystackreg
    - requests
    - scikit-beam >=0.0.17
    - scikit-image
    - scipy
    - six
    - tifffile

test:
  imports:
    - pyxrf
    - pyxrf.api
    - pyxrf.gui
    - pyxrf.model
    - pyxrf.model.command_tools
    - pyxrf.model.data_to_analysis_store
    - pyxrf.model.draw_image
    - pyxrf.model.draw_image_rgb
    - pyxrf.model.fileio
    - pyxrf.model.fit_spectrum
    - pyxrf.model.guessparam
    - pyxrf.model.lineplot
    - pyxrf.model.load_data_from_db
    - pyxrf.model.param_data
    - pyxrf.model.setting
    - pyxrf.model.utils
    - pyxrf.view
    - pyxrf.xanes_maps.xanes_maps_api

about:
  home: https://github.com/NSLS-II/pyxrf
  license: 3-Clause BSD
  license_family: BSD
  license_file: LICENSE
  summary: 'Python-based sophisticated fluorescence analysis package for fitting and visualizing X-ray fluorescence data'
